name: registro_estudiantes_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.18.1              # Para formateo de fechas (yyyy-MM-dd)
  sqflite: ^2.3.2+1          # Base de datos SQLite local
  path_provider: ^2.1.3      # Para obtener rutas locales del dispositivo
  # Opcional para responsive design:
  # flutter_screenutil: ^5.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
